"""esquema inicial

Revision ID: 1b463d5ec506
Revises:
Create Date: 2026-07-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b463d5ec506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('paciente', 'psicologo', name='rolusuario', native_enum=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)

    op.create_table('reportes_clinicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('generado_por_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id', 'version', name='uq_reporte_paciente_version')
    )
    with op.batch_alter_table('reportes_clinicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_clinicos_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('sesiones_conversacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'cerrada', 'escalada_crisis', name='estadosesion', native_enum=False, length=20), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones_conversacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_conversacion_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('vinculos_paciente_psicologo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('psicologo_id', sa.String(length=36), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id', 'psicologo_id', name='uq_vinculo_paciente_psicologo')
    )
    with op.batch_alter_table('vinculos_paciente_psicologo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vinculos_paciente_psicologo_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vinculos_paciente_psicologo_psicologo_id'), ['psicologo_id'], unique=False)

    op.create_table('mensajes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sesion_id', sa.String(length=36), nullable=False),
    sa.Column('remitente', sa.Enum('paciente', 'agente', name='remitentemensaje', native_enum=False, length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('emocion', sa.String(length=30), nullable=True),
    sa.Column('severidad', sa.String(length=30), nullable=True),
    sa.Column('crisis_detectada', sa.Boolean(), nullable=False),
    sa.Column('crisis_motivo', sa.String(length=255), nullable=True),
    sa.Column('plantilla_id', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_conversacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_sesion_id'), ['sesion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_creado_en'))

    op.drop_table('mensajes')
    with op.batch_alter_table('vinculos_paciente_psicologo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vinculos_paciente_psicologo_psicologo_id'))
        batch_op.drop_index(batch_op.f('ix_vinculos_paciente_psicologo_paciente_id'))

    op.drop_table('vinculos_paciente_psicologo')
    with op.batch_alter_table('sesiones_conversacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_conversacion_paciente_id'))

    op.drop_table('sesiones_conversacion')
    with op.batch_alter_table('reportes_clinicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_clinicos_paciente_id'))

    op.drop_table('reportes_clinicos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
